name: estacionamento_app
description: Aplicativo de monitoramento de vagas de estacionamento.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  flutter_map: ^8.1.1
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.0
  mqtt_client: ^10.2.0

  # Dependências adicionais podem ser adicionadas aqui futuramente


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    # Adicione imagens no diretório abaixo se desejar usar logos ou ícones
    # - assets/images/
